---

name: Differential ShellCheck

on:  # yamllint disable-line rule:truthy
  pull_request:

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@latest
        with:
          severity: warning
          token: ${{ secrets.GITHUB_TOKEN }}

...
